# Script pour BLAST

En traitement de données, les tableaux de données dans lequel vous cherchez certaines informations peuvent comporter des milliers de lignes et plusieurs centaines de colonnes. Considérant la taille de ces fichiers, l'utilisation d'Excel n'est généralement pas possible. C'est donc pour cela que les analystes font appel à R. 

Pour trouver vos séquences commencer par télécharger le fichier `séquences_inconnus.csv` et l'enregistrer dans le dossier `Documents`. Si vous enregistrer le document dans un autre dossier il vous faudra changer de répertoire de travail avec la fonction `setwd()`. Vous pouvez ensuite copier-collez ces commandes dans un nouveau script R. Suivant l'exécution de chacune des commandes vous devriez obtenir un fichier `mes_inconnus.csv` dans votre dossier de travail.  

```{r}
# Importer le fichier dans R 
raw_df = read.csv("sequences_inconnus.csv", header = TRUE, sep = ",", check.name = FALSE)

# Pour filtrer un tableau de données nous utilisons la fonction subset. Nous indiquons le nom de la 
# colonne dans laquelle nous voulons appliquer le filtre et quelles valeurs rechercher. Ici nous avons deux filtres de 
# recherche et donc nous utilisons le symbole & 
# Indiquer entre le guillements le jour de votre laboratoire (Mardi, Mercredi ou Jeudi, avec majuscule) et votre numéro d'équipe 
df = subset(raw_df, Laboratoire == "" & Equipe == "")

write.csv(df, file = "mes_inconnus.csv", quote = FALSE, row.names = FALSE)
```


