--- 
title: "BIA1401 - 2024 - Introduction à R"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
---

# Introduction

Ce petit guide à été rédigé à l'intention des élèves du cours BIA104 afin de familiariser les étudiants avec R et plus spécifiquement R Studio.  

1. La première section [Introduction à R et RStudio] présente brièvement R et R Studio. 

2. La seconde section [Scripter avec RStudio] explique comment élaborer des scripts avec RStudio et introduit quelques notions de bases. 

3. La troisième section [Script pour BLAST] comprend un script R que les étudiants doivent utiliser afin d'obtenir pour chacun de leurs inconnus la séquence d'acide nucléiques correspondant au gène ARNr 16S. Les étudiants pourront ensuite fournir les séquences à l'outil *Basic Local Alignment Search Tool* ([BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi)) du National Center for Biotechnology Information (NCBI) afin d'attribuer une classification taxonomique à chacun de leurs inconnus.

4. La quatrième section [R Markdown] aborde une différentes manière de rédiger ses scripts favorisant l'annotation et l'organisation du code en plus de l'exportation des scripts sous différents formats (PDF, HTML, etc.) pour le partage des scripts. Finalement, la section [Installer R et RStudio ] indique les liens pour télécharger chacun des programmes. 


